version: '3.7'

services:

  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: albon
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
