version: '3.7'

services:

  postgres:
    image: postgres:12.0-alpine
    ports:
      - '8080:8080'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: albon
      POSTGRES_DB: app